### ISSUE TITLE
口袋header的pa参数有时间限制，大佬有更好的解决方案吗

### ISSUE THREAD

**Issue by MowChann** [Miffy1030-llf/llf-bot#1]
简单测试得到
- pa参数在每次请求时数值都不一样
- pa参数修改一两个字符重放请求还能得到数据，但超过至少10分钟后会提示“请升级版本”
- pa参数在未登录时仍存在，可能是和设备信息有关的加密字符串

大佬还有可行的方案么

**Comment by Miffy1030-llf** [comment]
你好啊，我也只是刚发现这个现象，甚至了解的情况还没有你这么详细。也没有找到解决方案，如果你有解决方法，也希望赐教啊

**Comment by Miffy1030-llf** [comment]
> 简单测试得到
> 
> * pa参数在每次请求时数值都不一样
> * pa参数修改一两个字符重放请求还能得到数据，但超过至少10分钟后会提示“请升级版本”
> * pa参数在未登录时仍存在，可能是和设备信息有关的加密字符串
> 
> 大佬还有可行的方案么

pa参数应该是base64加密的，解密之后三个部分，有一个部分时时间戳，另外两个部分是什么我暂时也没有理解

**Comment by zhangpeng96** [comment]
> 你好啊，我也只是刚发现这个现象，甚至了解的情况还没有你这么详细。也没有找到解决方案，如果你有解决方法，也希望赐教啊

现在有大佬搞出来了，在header加一个`pa`参数，`pa`可以每次请求时更新，也可以10分钟刷新一次

https://github.com/chinshin/CQBot_hzx/blob/8d9d84efe5829fe8c6e61920015f629678a9b479/koudai48.py#L53-L60

欢迎其它问题继续交流~

**Comment by MowChann** [comment]
> 你好啊，我也只是刚发现这个现象，甚至了解的情况还没有你这么详细。也没有找到解决方案，如果你有解决方法，也希望赐教啊

现在有大佬搞出来了，在header加一个`pa`参数，`pa`可以每次请求时更新，也可以10分钟刷新一次

https://github.com/chinshin/CQBot_hzx/blob/8d9d84efe5829fe8c6e61920015f629678a9b479/koudai48.py#L53-L60

欢迎其它问题继续交流~

**Comment by Miffy1030-llf** [comment]
> > 你好啊，我也只是刚发现这个现象，甚至了解的情况还没有你这么详细。也没有找到解决方案，如果你有解决方法，也希望赐教啊
> 
> 现在有大佬搞出来了，在header加一个`pa`参数，`pa`可以每次请求时更新，也可以10分钟刷新一次
> 
> https://github.com/chinshin/CQBot_hzx/blob/8d9d84efe5829fe8c6e61920015f629678a9b479/koudai48.py#L53-L60
> 
> 欢迎其它问题继续交流~
这个方法我也想到来着，只是md5的字段没想到这么构造，一直没搞定。所以后来用了网易云信的sdk，从口袋的apk里找到了appkey，就不用每次都关注口袋的api了。

**Comment by Miffy1030-llf** [comment]
> > 你好啊，我也只是刚发现这个现象，甚至了解的情况还没有你这么详细。也没有找到解决方案，如果你有解决方法，也希望赐教啊
> 
> 现在有大佬搞出来了，在header加一个`pa`参数，`pa`可以每次请求时更新，也可以10分钟刷新一次
> 
> https://github.com/chinshin/CQBot_hzx/blob/8d9d84efe5829fe8c6e61920015f629678a9b479/koudai48.py#L53-L60
> 
> 欢迎其它问题继续交流~



这个方法我也想到来着，只是md5的字段没想到这么构造，一直没搞定。所以后来用了网易云信的sdk，从口袋的apk里找到了appkey，就不用每次都关注口袋的api了。
